spring.config.activate.on-profile=local

# Local MySQL explicit configuration
spring.datasource.url=${LOCAL_DB_URL:jdbc:mysql://localhost:3306/courtly?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${LOCAL_DB_USERNAME:root}
spring.datasource.password=${LOCAL_DB_PASSWORD:P\#dr0LS18J}
spring.datasource.driver-class-name=${LOCAL_DB_DRIVER:com.mysql.cj.jdbc.Driver}

# Hibernate settings for local development
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
